### ISSUE TITLE
Failing to convert -180,180 to 0,360 with gdal180to360

### ISSUE THREAD

**Issue by marosteg** [skiptoniam/sense#1]
I am trying to use **gdal180to360()** to convert the longitudes of a raster file (attached) but am getting a series of errors from the function. Help in trouble-shooting this would be greatly appreciated!:

```
gdal180to360("r.latlon.tif", "r360.tif")

ERROR 6: Too many command options 'compress=LZW'
Usage: gdal_translate [--help-general] [--long-usage]
       [-ot {Byte/Int16/UInt16/UInt32/Int32/UInt64/Int64/Float32/Float64/
             CInt16/CInt32/CFloat32/CFloat64}] [-strict]
       [-if format]* [-of format]
       [-b band] [-mask band] [-expand {gray|rgb|rgba}]
       [-outsize xsize[%]|0 ysize[%]|0] [-tr xres yres]
       [-r {nearest,bilinear,cubic,cubicspline,lanczos,average,mode}]
       [-unscale] [-scale[_bn] [src_min src_max [dst_min dst_max]]]* [-exponent[_bn] exp_val]*
       [-srcwin xoff yoff xsize ysize] [-epo] [-eco]
       [-projwin ulx uly lrx lry] [-projwin_srs srs_def]
       [-a_srs srs_def] [-a_coord_epoch epoch]
       [-a_ullr ulx uly lrx lry] [-a_nodata value]
       [-a_scale value] [-a_offset value]
       [-nogcp] [-gcp pixel line easting northing [elevation]]*
       |-colorinterp{_bn} {red|green|blue|alpha|gray|undefined}]
       |-colorinterp {red|green|blue|alpha|gray|undefined},...]
       [-mo "META-TAG=VALUE"]* [-q] [-sds]
       [-co "NAME=VALUE"]* [-stats] [-norat] [-noxmp]
       [-oo NAME=VALUE]*
       src_dataset dst_dataset
ERROR 6: Too many command options 'compress=LZW'
Usage: gdal_translate [--help-general] [--long-usage]
       [-ot {Byte/Int16/UInt16/UInt32/Int32/UInt64/Int64/Float32/Float64/
             CInt16/CInt32/CFloat32/CFloat64}] [-strict]
       [-if format]* [-of format]
       [-b band] [-mask band] [-expand {gray|rgb|rgba}]
       [-outsize xsize[%]|0 ysize[%]|0] [-tr xres yres]
       [-r {nearest,bilinear,cubic,cubicspline,lanczos,average,mode}]
       [-unscale] [-scale[_bn] [src_min src_max [dst_min dst_max]]]* [-exponent[_bn] exp_val]*
       [-srcwin xoff yoff xsize ysize] [-epo] [-eco]
       [-projwin ulx uly lrx lry] [-projwin_srs srs_def]
       [-a_srs srs_def] [-a_coord_epoch epoch]
       [-a_ullr ulx uly lrx lry] [-a_nodata value]
       [-a_scale value] [-a_offset value]
       [-nogcp] [-gcp pixel line easting northing [elevation]]*
       |-colorinterp{_bn} {red|green|blue|alpha|gray|undefined}]
       |-colorinterp {red|green|blue|alpha|gray|undefined},...]
       [-mo "META-TAG=VALUE"]* [-q] [-sds]
       [-co "NAME=VALUE"]* [-stats] [-norat] [-noxmp]
       [-oo NAME=VALUE]*
       src_dataset dst_dataset
ERROR 4: /var/folders/r_/07130lm5719fdlg_wmd9qdvw0000gn/T//Rtmpeu6rGU/1e8674e5d9cd/tmp1e861e3e5db0L.tif: No such file or directory
ERROR 4: /var/folders/r_/07130lm5719fdlg_wmd9qdvw0000gn/T//Rtmpeu6rGU/1e8674e5d9cd/tmp1e861e3e5db0R.tif: No such file or directory
ERROR 4: compress=LZW: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/gdal_merge.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.10/site-packages/osgeo_utils/gdal_merge.py", line 544, in main
    return gdal_merge(argv)
  File "/usr/local/lib/python3.10/site-packages/osgeo_utils/gdal_merge.py", line 428, in gdal_merge
    ulx = file_infos[0].ulx
IndexError: list index out of range
rm: /var/folders/r_/07130lm5719fdlg_wmd9qdvw0000gn/T//Rtmpeu6rGU/1e8674e5d9cd/tmp1e861e3e5db0R.tif: No such file or directory
rm: /var/folders/r_/07130lm5719fdlg_wmd9qdvw0000gn/T//Rtmpeu6rGU/1e8674e5d9cd/tmp1e861e3e5db0L.tif: No such file or directory
```

[r.latlon.tif.zip](https://github.com/skiptoniam/geostuff/files/12110355/r.latlon.tif.zip)

**Comment by skiptoniam** [comment]
hmm not sure. I'll have to have a look. In the meantime you can use `terra::rotate(r,left=TRUE)`
